format = '''ğŸ’€ $username$hostname$directory $git_branch-$time$character'''

scan_timeout = 10
add_newline = false


[character] 
disabled = false
success_symbol = '[ \$](bold green)'
error_symbol = '[ \$](bold red)'


[cmd_duration]
show_milliseconds = false
format = 'â²ï¸ [$duration]($style)'
show_notifications = true
min_time_to_notify = 15


[directory]#
style = 'bold blue'
disabled = false
format = 'at [$path]($style)'



[fill]
disabled = false
symbol = '-'
style = '#878787'


[git_branch]
disabled = false


[hostname]
disabled = false
ssh_only = true
format = 'on [ğŸŒ$hostname ](bold green)'


[time]
disabled = false
time_format = "%R"
utc_time_offset = "local"
format = '[ $time ](bold blue)'
style = 'bg:#303030'


[username]
disabled = false
show_always = true
style_root = 'bold red'
style_user = 'bold green'
format = '[$user ]($style)'
